title: "Practical Cyber-Ops Fundamentals"
description: "Security CTF handbook"

remote_theme: just-the-docs/just-the-docs   # :contentReference[oaicite:0]{index=0}

plugins:
  - jekyll-remote-theme

baseurl: ""          
color_scheme: dark  

